#include "client_lua_api.h"

#include "../input/input_state.h"
#include <SFML/Window/Keyboard.hpp>
#include <common/lua/script_engine.h>

namespace {
    void initMouseControlApi(sol::table& inputTable, sf::Window& window,
                             InputState& inputState)
    {
        inputTable["hideMouse"] = [&window, &inputState]() {
            window.setMouseCursorVisible(false);
            inputState.isMouseLocked = true;
        };
        inputTable["showMouse"] = [&window, &inputState]() {
            window.setMouseCursorVisible(true);
            inputState.isMouseLocked = false;
        };
    }

    void initKeysApi(ScriptEngine& scriptEngine);
} // namespace

void luaInitInputApi(ScriptEngine& scriptEngine, sf::Window& window,
                     InputState& inputState)
{
    auto inputTable = scriptEngine.addTable("input");
    initMouseControlApi(inputTable, window, inputState);
    initKeysApi(scriptEngine);
}

namespace {
    void initKeysApi(ScriptEngine& scriptEngine)
    {
        // Don't worry, this code is generated by a python script lol
        auto keys = scriptEngine.addTable("Keyboard");
        keys["A"] = sf::Keyboard::Key::A;
        keys["B"] = sf::Keyboard::Key::B;
        keys["C"] = sf::Keyboard::Key::C;
        keys["D"] = sf::Keyboard::Key::D;
        keys["E"] = sf::Keyboard::Key::E;
        keys["F"] = sf::Keyboard::Key::F;
        keys["G"] = sf::Keyboard::Key::G;
        keys["H"] = sf::Keyboard::Key::H;
        keys["I"] = sf::Keyboard::Key::I;
        keys["J"] = sf::Keyboard::Key::J;
        keys["K"] = sf::Keyboard::Key::K;
        keys["L"] = sf::Keyboard::Key::L;
        keys["M"] = sf::Keyboard::Key::M;
        keys["N"] = sf::Keyboard::Key::N;
        keys["O"] = sf::Keyboard::Key::O;
        keys["P"] = sf::Keyboard::Key::P;
        keys["Q"] = sf::Keyboard::Key::Q;
        keys["R"] = sf::Keyboard::Key::R;
        keys["S"] = sf::Keyboard::Key::S;
        keys["T"] = sf::Keyboard::Key::T;
        keys["U"] = sf::Keyboard::Key::U;
        keys["V"] = sf::Keyboard::Key::V;
        keys["W"] = sf::Keyboard::Key::W;
        keys["X"] = sf::Keyboard::Key::X;
        keys["Y"] = sf::Keyboard::Key::Y;
        keys["Z"] = sf::Keyboard::Key::Z;
        keys["Num0"] = sf::Keyboard::Key::Num0;
        keys["Num1"] = sf::Keyboard::Key::Num1;
        keys["Num2"] = sf::Keyboard::Key::Num2;
        keys["Num3"] = sf::Keyboard::Key::Num3;
        keys["Num4"] = sf::Keyboard::Key::Num4;
        keys["Num5"] = sf::Keyboard::Key::Num5;
        keys["Num6"] = sf::Keyboard::Key::Num6;
        keys["Num7"] = sf::Keyboard::Key::Num7;
        keys["Num8"] = sf::Keyboard::Key::Num8;
        keys["Num9"] = sf::Keyboard::Key::Num9;
        keys["Escape"] = sf::Keyboard::Key::Escape;
        keys["LControl"] = sf::Keyboard::Key::LControl;
        keys["LShift"] = sf::Keyboard::Key::LShift;
        keys["LAlt"] = sf::Keyboard::Key::LAlt;
        keys["LSystem"] = sf::Keyboard::Key::LSystem;
        keys["RControl"] = sf::Keyboard::Key::RControl;
        keys["RShift"] = sf::Keyboard::Key::RShift;
        keys["RAlt"] = sf::Keyboard::Key::RAlt;
        keys["RSystem"] = sf::Keyboard::Key::RSystem;
        keys["Menu"] = sf::Keyboard::Key::Menu;
        keys["LBracket"] = sf::Keyboard::Key::LBracket;
        keys["RBracket"] = sf::Keyboard::Key::RBracket;
        keys["Semicolon"] = sf::Keyboard::Key::Semicolon;
        keys["Comma"] = sf::Keyboard::Key::Comma;
        keys["Period"] = sf::Keyboard::Key::Period;
        keys["Quote"] = sf::Keyboard::Key::Apostrophe;
        keys["Slash"] = sf::Keyboard::Key::Slash;
        keys["Backslash"] = sf::Keyboard::Key::Backslash;
        keys["Tilde"] = sf::Keyboard::Key::Grave;
        keys["Equal"] = sf::Keyboard::Key::Equal;
        keys["Dash"] = sf::Keyboard::Key::Hyphen;
        keys["Space"] = sf::Keyboard::Key::Space;
        keys["Enter"] = sf::Keyboard::Key::Enter;
        keys["BackSpace"] = sf::Keyboard::Key::Backspace;
        keys["Tab"] = sf::Keyboard::Key::Tab;
        keys["PageUp"] = sf::Keyboard::Key::PageUp;
        keys["PageDown"] = sf::Keyboard::Key::PageDown;
        keys["End"] = sf::Keyboard::Key::End;
        keys["Home"] = sf::Keyboard::Key::Home;
        keys["Insert"] = sf::Keyboard::Key::Insert;
        keys["Delete"] = sf::Keyboard::Key::Delete;
        keys["Add"] = sf::Keyboard::Key::Add;
        keys["Subtract"] = sf::Keyboard::Key::Subtract;
        keys["Multiply"] = sf::Keyboard::Key::Multiply;
        keys["Divide"] = sf::Keyboard::Key::Divide;
        keys["Left"] = sf::Keyboard::Key::Left;
        keys["Right"] = sf::Keyboard::Key::Right;
        keys["Up"] = sf::Keyboard::Key::Up;
        keys["Down"] = sf::Keyboard::Key::Down;
        keys["Numpad0"] = sf::Keyboard::Key::Numpad0;
        keys["Numpad1"] = sf::Keyboard::Key::Numpad1;
        keys["Numpad2"] = sf::Keyboard::Key::Numpad2;
        keys["Numpad3"] = sf::Keyboard::Key::Numpad3;
        keys["Numpad4"] = sf::Keyboard::Key::Numpad4;
        keys["Numpad5"] = sf::Keyboard::Key::Numpad5;
        keys["Numpad6"] = sf::Keyboard::Key::Numpad6;
        keys["Numpad7"] = sf::Keyboard::Key::Numpad7;
        keys["Numpad8"] = sf::Keyboard::Key::Numpad8;
        keys["Numpad9"] = sf::Keyboard::Key::Numpad9;
        keys["F1"] = sf::Keyboard::Key::F1;
        keys["F2"] = sf::Keyboard::Key::F2;
        keys["F3"] = sf::Keyboard::Key::F3;
        keys["F4"] = sf::Keyboard::Key::F4;
        keys["F5"] = sf::Keyboard::Key::F5;
        keys["F6"] = sf::Keyboard::Key::F6;
        keys["F7"] = sf::Keyboard::Key::F7;
        keys["F8"] = sf::Keyboard::Key::F8;
        keys["F9"] = sf::Keyboard::Key::F9;
        keys["F10"] = sf::Keyboard::Key::F10;
        keys["F11"] = sf::Keyboard::Key::F11;
        keys["F12"] = sf::Keyboard::Key::F12;
        keys["F13"] = sf::Keyboard::Key::F13;
        keys["F14"] = sf::Keyboard::Key::F14;
        keys["F15"] = sf::Keyboard::Key::F15;
        keys["Pause"] = sf::Keyboard::Key::Pause;
    }
} // namespace
